const genreImportedIds = require('../data/genreIds.js');
const prediction = require('@google-cloud/prediction')({
  projectId: 'backc-179222',
  keyFilename: '../backc-73ac68e09be6.json'
});

var model = prediction.model('movie-prefers');

// api JSON has a results property that is an array of results (movies)
// data.results[i].genre_ids is an array of ids
  // loop thru array of IDs and train model with each ID and the data.results[i].overview as statement

// pass in .train as cb?
module.exports = {
  googleTrain: function(data) {
    data.results.forEach((element, index) => {
      element.genre_ids.forEach((id, index) => {
        model.train(genreImportedIds['' + id], element.overview).then(function(data) {
          console.log('Successfully trained inside googleTrain', data);
        })
      })
    })
  }
}

var dummyAPIres =
{ page: 1,
  total_results: 104,
  total_pages: 6,
  results: 
   [ { vote_count: 7,
       id: 438058,
       video: false,
       vote_average: 6.1,
       title: 'Detective Conan: Crimson Love Letter',
       popularity: 16.881305,
       poster_path: '/shpjDVjugLMoc4Wt1eRdueH5IOf.jpg',
       original_language: 'id',
       original_title: '劇場版『名探偵コナン から紅の恋歌』',
       genre_ids: [Object],
       backdrop_path: '/raqKNnppsAHEhOptz5cQCJ7ktpX.jpg',
       adult: false,
       overview: 'Bombing case at Nichiuri TV in autumn. The Satsuki Cup, which crowns the winner of Japan\'s Hyakunin Isshu, is currently being filmed inside the facility. The incident results in a big commotion and, while the building is burning to ashes, the only people left inside are Hattori and Toyama Kazuha. They get rescued just in time by Conan , who rushes to the scene. Both the identity and purposes of the bomber are unknown.',
       release_date: '2017-04-15' },
     { vote_count: 1451,
       id: 856,
       video: false,
       vote_average: 7.2,
       title: 'Who Framed Roger Rabbit',
       popularity: 14.298901,
       poster_path: '/lYfRc57Kx9VgLZ48iulu0HKnM15.jpg',
       original_language: 'en',
       original_title: 'Who Framed Roger Rabbit',
       genre_ids: [Object],
       backdrop_path: '/9podqGmd36AJHO13HQIQHQZRTJC.jpg',
       adult: false,
       overview: '\'Toon star Roger is worried that his wife Jessica is playing pattycake with someone else, so the studio hires detective Eddie Valiant to snoop on her. But the stakes are quickly raised when Marvin Acme is found dead and Roger is the prime suspect.',
       release_date: '1988-06-21' },
     { vote_count: 77,
       id: 18874,
       video: false,
       vote_average: 7.8,
       title: 'Ghost in the Shell: Stand Alone Complex - Solid State Society',
       popularity: 7.548847,
       poster_path: '/xIrtzclUkDkFytdIZpu7fppyRbO.jpg',
       original_language: 'ja',
       original_title: 'Kôkaku kidôtai: Stand Alone Complex - Solid State Society',
       genre_ids: [Object],
       backdrop_path: '/fH5oiUyCzw1ut0iaZ9OIw1pELU6.jpg',
       adult: false,
       overview: 'The story takes place in the year 2034, two years after the events in Ghost in the Shell: S.A.C. 2nd GIG. Female cyborg Major Motoko Kusanagi has left Public Security Section 9, an elite counter-terrorist and anti-crime unit specializing in cyber-warfare, which has expanded to a team of 20 field operatives with Togusa acting as the field lead.',
       release_date: '2007-02-23' },
     { vote_count: 478,
       id: 382322,
       video: false,
       vote_average: 6.2,
       title: 'Batman: The Killing Joke',
       popularity: 7.488277,
       poster_path: '/zm0ODjtfJfJW0W269LqsQl5OhJ8.jpg',
       original_language: 'en',
       original_title: 'Batman: The Killing Joke',
       genre_ids: [Object],
       backdrop_path: '/iYrE2zV1DfZ3l7Lh4frHzNwFncq.jpg',
       adult: false,
       overview: 'As Batman hunts for the escaped Joker, the Clown Prince of Crime attacks the Gordon family to prove a diabolical point mirroring his own fall into madness. Based on the graphic novel by Alan Moore and Brian Bolland.',
       release_date: '2016-07-21' },
     { vote_count: 297,
       id: 242643,
       video: false,
       vote_average: 7.3,
       title: 'Batman: Assault on Arkham',
       popularity: 7.0955,
       poster_path: '/jY5DEgyMmHUh4AbWTu6pOb5g7vk.jpg',
       original_language: 'en',
       original_title: 'Batman: Assault on Arkham',
       genre_ids: [Object],
       backdrop_path: '/rZhblFe1Y9IheA47fO3i0b0qdvt.jpg',
       adult: false,
       overview: 'Based on the hit video game series, Batman must find a bomb planted by the Joker while dealing with a mysterious team of villains called, The Suicide Squad.',
       release_date: '2014-08-12' },
     { vote_count: 48,
       id: 381028,
       video: false,
       vote_average: 8.1,
       title: 'Tower',
       popularity: 6.793238,
       poster_path: '/iOiwQLTQe1fwC8ihoCaXBHjGz2J.jpg',
       original_language: 'en',
       original_title: 'Tower',
       genre_ids: [Object],
       backdrop_path: '/9oCJTvMi0rq22zv4JnnAuCAVytg.jpg',
       adult: false,
       overview: 'Combining archival footage with rotoscopic animation, Tower reveals the action-packed untold stories of the witnesses, heroes and survivors of America’s first mass school shooting, when the worst in one man brought out the best in so many others.',
       release_date: '2016-03-13' },
     { vote_count: 253,
       id: 69735,
       video: false,
       vote_average: 7.1,
       title: 'Batman: Year One',
       popularity: 6.031094,
       poster_path: '/bI1YVuhBN6Vws1GP9Mf01DyhC2s.jpg',
       original_language: 'en',
       original_title: 'Batman: Year One',
       genre_ids: [Object],
       backdrop_path: '/hAhMOPPPxzCKsCu5rUMYdwS8Yb5.jpg',
       adult: false,
       overview: 'Two men come to Gotham City: Bruce Wayne after years abroad feeding his lifelong obsession for justice and Jim Gordon after being too honest a cop with the wrong people elsewhere. After learning painful lessons about the city\'s corruption on its streets and police department respectively, this pair learn how to fight back their own way. With that, Gotham\'s evildoers from top to bottom are terrorized by the mysterious Batman and the equally heroic Gordon is assigned to catch him by comrades who both hate and fear him themselves. In the ensuing manhunt, both find much in common as the seeds of an unexpected friendship are laid with additional friends and rivals helping to start the legend.',
       release_date: '2011-09-27' },
     { vote_count: 79,
       id: 15805,
       video: false,
       vote_average: 6.9,
       title: 'Batman & Mr. Freeze: SubZero',
       popularity: 6.010226,
       poster_path: '/6Leq7SqNEuCNVr3fiykDVWf6Z8g.jpg',
       original_language: 'en',
       original_title: 'Batman & Mr. Freeze: SubZero',
       genre_ids: [Object],
       backdrop_path: '/yGipWTfWvrMR0sotpypKQeFUzIu.jpg',
       adult: false,
       overview: 'When a desperate Mr. Freeze, to save his dying wife, kidnaps Barbara (Batgirl) Gordon as an involuntary organ donor, Batman and Robin must find her before the operation can begin.',
       release_date: '1998-03-17' },
     { vote_count: 4,
       id: 339877,
       video: false,
       vote_average: 6,
       title: 'Loving Vincent',
       popularity: 5.921456,
       poster_path: '/qlrhwUDe7YOZujAYanK6ij2vbY5.jpg',
       original_language: 'en',
       original_title: 'Loving Vincent',
       genre_ids: [Object],
       backdrop_path: '/diwcbtecMHIi1zPRm2PbibEixph.jpg',
       adult: false,
       overview: 'A painted animated Biopic about world-renowned artist Vincent van Gogh.',
       release_date: '2017-09-22' },
     { vote_count: 39,
       id: 239529,
       video: false,
       vote_average: 6.5,
       title: 'Lupin the Third vs. Detective Conan: The Movie',
       popularity: 5.397567,
       poster_path: '/nzv1xO1FsiVb51AgFKEPt4g8kjd.jpg',
       original_language: 'ko',
       original_title: 'Lupin Sansei Tai Meitantei Conan the Movie',
       genre_ids: [Object],
       backdrop_path: '/yCvieSjLjo9sXHXDzYeuollEaOd.jpg',
       adult: false,
       overview: 'The plot follows Conan Edogawa who sets out to apprehend Arsène Lupin III, the suspect of stealing a jewel called Cherry Sapphire.',
       release_date: '2013-12-07' },
     { vote_count: 32,
       id: 21422,
       video: false,
       vote_average: 7.1,
       title: 'Detective Conan: Skyscraper on a Timer',
       popularity: 5.167551,
       poster_path: '/gwdpUWuHREweHmvruNrtdmzAoZR.jpg',
       original_language: 'ja',
       original_title: '名探偵コナン 時計じかけの摩天楼',
       genre_ids: [Object],
       backdrop_path: '/i1xRdsmZNufZv2m00sDO68cMoU4.jpg',
       adult: false,
       overview: 'Shinichi is invited to a party held by a famous architect and Shinichi asks Ran to go instead. There a mysterious person plants a lot of bombs and gives Shinichi clues as to the location of the bombs. Shinichi tries to uncover all the bombs and save Ran\'s life.',
       release_date: '1997-04-19' },
     { vote_count: 30,
       id: 18839,
       video: false,
       vote_average: 7.9,
       title: 'Ghost in the Shell: Stand Alone Complex - The Laughing Man',
       popularity: 5.099225,
       poster_path: '/ifM2yn7wufU7cNH5ew8oSA1x5OT.jpg',
       original_language: 'ja',
       original_title: '攻殻機動隊 Stand Alone Complex The Laughing Man',
       genre_ids: [Object],
       backdrop_path: '/l09pMW9SJHZUMNYRYecaeh7r4EC.jpg',
       adult: false,
       overview: 'The year is 2030 and six years have passed since a criminal known only as "The Laughing Man" swept through top medical nanotechnology firms committing acts of cyber-terrorism, kidnapping, and espionage leaving no known suspects. New information is revealed, as Section 9 enters the hunt for a suspect capable of unfathomable actions in this compilation of Stand Alone Complex content.',
       release_date: '2005-01-01' },
     { vote_count: 30,
       id: 20677,
       video: false,
       vote_average: 7.4,
       title: 'Detective Conan: Captured in Her Eyes',
       popularity: 4.624056,
       poster_path: '/uE0vKNE4sOX4rtsln7UV4Z5C7Rr.jpg',
       original_language: 'ja',
       original_title: '名探偵コナン 瞳の中の暗殺者',
       genre_ids: [Object],
       backdrop_path: '/3reaoqvRnal2J0wKrety6HbxYva.jpg',
       adult: false,
       overview: 'Police officers around Tokyo are being murdered by an unknown assailant. When Ran witnesses an attempt on the life of one of her friends in the police, she loses her memory. Now, Conan and Inspector Megure must find the murderer while Ran attempts to regain her lost memories.',
       release_date: '2000-04-22' },
     { vote_count: 50,
       id: 196750,
       video: false,
       vote_average: 7.1,
       title: 'Ghost in the Shell Arise - Border 1: Ghost Pain',
       popularity: 4.552425,
       poster_path: '/4iDuwS19O2GIXTRvUR9xgNdEKh2.jpg',
       original_language: 'ja',
       original_title: '攻殻機動隊ARISE border : 1 Ghost Pain',
       genre_ids: [Object],
       backdrop_path: '/7A4KN1Bz6sg4hY06JRHJC1KeeRl.jpg',
       adult: false,
       overview: 'The story is set in 2027, one year after the end of the fourth non-nuclear war. New Port City is still reeling from the war\'s aftermath when it suffers a bombing caused by a self-propelled mine. Then, a military member implicated in arms-dealing bribes is gunned down.  During the investigation, Public Security Section\'s Daisuke Aramaki encounters Motoko Kusanagi, the cyborg, wizard-level hacker assigned to the military\'s 501st Secret Unit. Batou, a man with the "eye that does not sleep," suspects that Kusanagi is the one behind the bombing. The Niihama Prefectural Police detective Togusa is pursuing his own dual cases of the shooting death and a prostitute\'s murder. Motoko herself is being watched by the 501st Secret Unit\'s head Kurutsu and cyborg agents.',
       release_date: '2013-06-22' },
     { vote_count: 26,
       id: 39207,
       video: false,
       vote_average: 7.4,
       title: 'Detective Conan: Full Score of Fear',
       popularity: 3.970646,
       poster_path: '/ylWngGZTeaIZDEe8UcHQBViwfIh.jpg',
       original_language: 'ja',
       original_title: '名探偵コナン 戦慄の楽譜（フルスコア）',
       genre_ids: [Object],
       backdrop_path: '/7NCZLBL3NN771SG1t6qp936ioox.jpg',
       adult: false,
       overview: 'Serial murders involving all kinds have happened. All the victims are from a Music School led by a famous pianist. Conan and company have been invited to a opening concert of the Music Hall built by the pianist. The biggest attraction of this concert is the world famous violin called "Stradivarius" and a special appearance of a singer who has perfect pitch.',
       release_date: '2008-04-19' },
     { vote_count: 31,
       id: 28764,
       video: false,
       vote_average: 7.9,
       title: 'Detective Conan: The Raven Chaser',
       popularity: 3.404764,
       poster_path: '/cH19PY2mnhoUc2qrB71KlFOHUMY.jpg',
       original_language: 'ja',
       original_title: '名探偵コナン 漆黒の追跡者（チェイサー）',
       genre_ids: [Object],
       backdrop_path: '/2jNj5RAavrjas5JqjpKnw7x3myz.jpg',
       adult: false,
       overview: 'A new member from the Black Organization that shrunk Shinichi\'s body manages to find out about Shinichi\'s transformation into Conan. This discovery starts to put those around him in danger as Gin and the other Black Organization members start to take action.',
       release_date: '2009-04-18' },
     { vote_count: 36,
       id: 51482,
       video: false,
       vote_average: 8,
       title: 'Death Note Relight 1: Visions of a God',
       popularity: 3.322226,
       poster_path: '/f8EloiCx5go0ChcZNTSHCfBoZwc.jpg',
       original_language: 'ja',
       original_title: 'Death Note: デスノート',
       genre_ids: [Object],
       backdrop_path: '/A2OkQIOOkH8u8c8NjvEUbq8cC51.jpg',
       adult: false,
       overview: 'Yagami Light is an ace student with great prospects, who\'s bored out of his mind. One day he finds the "Death Note": a notebook from the realm of the Death Gods, with the power to kill people in any way he desires. With the Death Note in hand, Light decides to create his perfect world, without crime or criminals. However, when criminals start dropping dead one by one, the authorites send the legendary detective L to track down the killer, and a battle of wits, deception and logic ensues...this was aired on Japanese tv shortly after the death note anime was completed, this special basically re-cuts the first 26 episodes of the series into a two hour movie with some new scenes and dialogue added and the story is seen from ryuk\'s viewpoint.',
       release_date: '2009-09-23' },
     { vote_count: 24,
       id: 316873,
       video: false,
       vote_average: 6.5,
       title: 'Detective Conan: Sunflowers of Inferno',
       popularity: 3.319204,
       poster_path: '/oQ6Afimj9b1vPJ5J2J1hALtqdcZ.jpg',
       original_language: 'ja',
       original_title: '名探偵コナン 業火の向日葵',
       genre_ids: [Object],
       backdrop_path: '/4DQ5tM57pUhp1WnqjFwEIsgxhMV.jpg',
       adult: false,
       overview: 'Conan tries to track down Kaito Kid, who supposedly steals a replica of one of Van Gogh\'s Sunflowers paintings during an auction.',
       release_date: '2015-04-18' },
     { vote_count: 15,
       id: 23153,
       video: false,
       vote_average: 7,
       title: 'The Garden of Sinners - Chapter 3: Remaining Sense of Pain',
       popularity: 3.222614,
       poster_path: '/sXVwH7hQBmtjXLoOokxZzkdCVbL.jpg',
       original_language: 'ja',
       original_title: '劇場版「空の境界」第三章 痛覚残留',
       genre_ids: [Object],
       backdrop_path: '/fsOQi5vtkZ10GvkUn7zfhkM7Tmg.jpg',
       adult: false,
       overview: 'July 1998 - After a group of delinquents is found dead in their hangout place with all their limbs twisted and torn off, Aozaki Touko receives a request to find the murderer and asks Shiki for help. The main suspect is Asagami Fujino; a girl who was the boys\' plaything until recently, who Shiki believes to be "one of her kind".',
       release_date: '2008-02-09' },
     { vote_count: 14,
       id: 23151,
       video: false,
       vote_average: 7.3,
       title: 'The Garden of Sinners - Chapter 2: A Study in Murder (Part 1)',
       popularity: 3.079812,
       poster_path: '/rK7ju10alpaGZ4cdKyjR4OPFxPK.jpg',
       original_language: 'ja',
       original_title: '劇場版「空の境界」第二章 殺人考察（前）',
       genre_ids: [Object],
       backdrop_path: '/pke7LGEqaaugzHoDQmGHMD1HD2H.jpg',
       adult: false,
       overview: 'August 1995: Mikiya first meets Shiki in a white kimono during a snowing day. Later on, at the high school freshmen ceremony, Mikiya sees Shiki in the crowd and chases after her, introducing himself to her. But Shiki hides a big secret: A wave of bizarre murders occur around many loose ends, and no suspects. there are still many questions: Who to believe? Who is the murderer? What is the secret of Shiki? and especially: Who is SHIKI?',
       release_date: '2007-12-29' } ] }
